name: "Build the extension and create a zip"

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install packages
        run: npm install

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Build vsix
        run: vsce package --no-git-tag-version --out gha-pin-actions.vsix

      - name: Upload vsix artifact
        uses: actions/upload-artifact@v6
        with:
          name: gha-pin-actions
          path: gha-pin-actions.vsix
