name: "Build the extension"

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'

      - name: Install packages
        run: npm install

      - name: Compile TypeScript
        run: npm run compile

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Build vsix
        run: vsce package --no-git-tag-version --allow-missing-repository --out gha-pin-actions.vsix

      - name: Upload vsix artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: gha-pin-actions
          path: gha-pin-actions.vsix
